import { useEffect, useMemo, useState } from 'react';

const autoGeneratedFields = new Set(['id', '_rowid_', 'claim_number', 'data_zgloszenia', 'status', 'utworzono', 'dzial', 'dept']);

const mainListSpec = [
  { label: 'CLAIM_NUMBER', aliases: ['claim_number'] },
  { label: 'KKW', aliases: ['kkw'] },
  { label: 'KOD_WYROBU', aliases: ['kod_wyrobu'] },
  { label: 'NAZWA_WYROBU', aliases: ['nazwa_wyrobu'] },
  { label: 'TYTUL', aliases: ['tytul', 'tytul_zgloszenia'] },
  { label: 'ILOSC', aliases: ['ilosc'] },
  { label: 'STATUS', aliases: ['status'] },
  { label: 'ZGLASZAJACY', aliases: ['zglaszajacy'] },
  { label: 'DZIAL', aliases: ['dept', 'dzial'] },
  { label: 'UTWORZONO', aliases: ['utworzono'] }
];

const hiddenMainListColumns = new Set(['_rowid_', 'id', 'opis', 'data_zgloszenia']);
const showAutoFieldsSection = false;

function App() {
  const [claims, setClaims] = useState([]);
  const [schema, setSchema] = useState([]);
  const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const [token, setToken] = useState(() => localStorage.getItem('claims_token') || '');
  const [user, setUser] = useState(null);
  const [loginForm, setLoginForm] = useState({ username: '', password: '' });
  const [authLoading, setAuthLoading] = useState(false);

  const [editingClaim, setEditingClaim] = useState(null);
  const [editDraft, setEditDraft] = useState({});
  const [isSaving, setIsSaving] = useState(false);
  const [isAddModalOpen, setIsAddModalOpen] = useState(false);
  const [newClaimDraft, setNewClaimDraft] = useState({});
  const [isCreating, setIsCreating] = useState(false);
  const [deletingRowId, setDeletingRowId] = useState(null);

  function clearAuth() {
    localStorage.removeItem('claims_token');
    setToken('');
    setUser(null);
    setClaims([]);
    setSchema([]);
  }

  async function authFetch(url, options = {}) {
    const headers = {
      ...(options.headers || {})
    };

    if (token) {
      headers.Authorization = `Bearer ${token}`;
    }

    const response = await fetch(url, {
      ...options,
      headers
    });

    if (response.status === 401) {
      clearAuth();
      throw new Error('Session expired. Please login again.');
    }

    return response;
  }

  useEffect(() => {
    async function validateSessionAndLoad() {
      if (!token) {
        setLoading(false);
        return;
      }

      setLoading(true);
      setError('');

      try {
        const meResponse = await authFetch('/api/auth/me');
        if (!meResponse.ok) {
          throw new Error('Could not validate session');
        }
        const meData = await meResponse.json();
        setUser(meData.user);

        const [claimsResponse, schemaResponse] = await Promise.all([
          authFetch('/api/claims'),
          authFetch('/api/claims/schema')
        ]);

        if (!claimsResponse.ok) {
          throw new Error('Could not load claims');
        }
        if (!schemaResponse.ok) {
          throw new Error('Could not load schema');
        }

        const claimsData = await claimsResponse.json();
        const schemaData = await schemaResponse.json();

        setClaims(claimsData);
        setSchema(Array.isArray(schemaData) ? schemaData : []);
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    }

    validateSessionAndLoad();
  }, [token]);

  async function login(event) {
    event.preventDefault();
    setAuthLoading(true);
    setError('');

    try {
      const response = await fetch('/api/auth/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(loginForm)
      });

      const payload = await response.json().catch(() => ({}));
      if (!response.ok) {
        throw new Error(payload.error || 'Login failed');
      }

      localStorage.setItem('claims_token', payload.token);
      setToken(payload.token);
      setUser(payload.user);
      setLoginForm({ username: '', password: '' });
    } catch (err) {
      setError(err.message);
    } finally {
      setAuthLoading(false);
    }
  }

  async function logout() {
    try {
      if (token) {
        await authFetch('/api/auth/logout', { method: 'POST' });
      }
    } catch {
      // Ignore network/logout errors and clear local auth anyway.
    } finally {
      clearAuth();
      setError('');
    }
  }

  const columns = useMemo(() => {
    if (claims[0]) {
      return Object.keys(claims[0]);
    }

    if (!schema.length) {
      return [];
    }

    return ['_rowid_', ...schema.map((column) => column.name)];
  }, [claims, schema]);

  const editableColumns = useMemo(() => columns.filter((column) => column !== '_rowid_'), [columns]);

  const displayColumns = useMemo(() => {
    const lowerToActual = new Map();
    columns.forEach((column) => {
      const lower = column.toLowerCase();
      if (!hiddenMainListColumns.has(lower) && !lowerToActual.has(lower)) {
        lowerToActual.set(lower, column);
      }
    });

    return mainListSpec
      .map((spec) => {
        const source = spec.aliases.map((alias) => lowerToActual.get(alias)).find(Boolean);

        if (source) {
          return {
            key: source,
            source,
            lowerSource: source.toLowerCase(),
            label: spec.label
          };
        }

        if (spec.label === 'DZIAL' && user?.dept) {
          return {
            key: '__dept__',
            source: '__dept__',
            lowerSource: '__dept__',
            label: 'DZIAL'
          };
        }

        return null;
      })
      .filter(Boolean);
  }, [columns, user]);

  const addFormColumns = useMemo(() => {
    if (schema.length) {
      return schema
        .map((column) => column.name)
        .filter((column) => !autoGeneratedFields.has(column.toLowerCase()) && !['zglaszajacy', 'dept', 'dzial'].includes(column.toLowerCase()));
    }

    return editableColumns.filter((column) => !autoGeneratedFields.has(column.toLowerCase()) && !['zglaszajacy', 'dept', 'dzial'].includes(column.toLowerCase()));
  }, [editableColumns, schema]);

  const filteredClaims = useMemo(() => {
    if (!query.trim()) {
      return claims;
    }

    const needle = query.toLowerCase();
    return claims.filter((claim) =>
      Object.values(claim).some((value) => String(value ?? '').toLowerCase().includes(needle))
    );
  }, [claims, query]);

  function openEditModal(claim) {
    setEditingClaim(claim);
    const draft = {};
    editableColumns.forEach((column) => {
      draft[column] = String(claim[column] ?? '');
    });
    setEditDraft(draft);
    setError('');
  }

  function closeEditModal() {
    setEditingClaim(null);
    setEditDraft({});
    setIsSaving(false);
  }

  function openAddModal() {
    const draft = {};
    addFormColumns.forEach((column) => {
      draft[column] = '';
    });
    setNewClaimDraft(draft);
    setIsAddModalOpen(true);
    setError('');
  }

  function closeAddModal() {
    setIsAddModalOpen(false);
    setNewClaimDraft({});
    setIsCreating(false);
  }

  async function createClaim() {
    setIsCreating(true);
    setError('');

    try {
      const response = await authFetch('/api/claims', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(newClaimDraft)
      });

      const payload = await response.json().catch(() => ({}));
      if (!response.ok) {
        throw new Error(payload.error || 'Failed to create claim');
      }

      setClaims((previous) => [payload, ...previous]);
      closeAddModal();
    } catch (err) {
      setError(err.message);
      setIsCreating(false);
    }
  }


  async function deleteClaim(rowId) {
    const confirmed = window.confirm('Czy na pewno usunąć tę reklamację?');
    if (!confirmed) {
      return;
    }

    setDeletingRowId(rowId);
    setError('');

    try {
      const response = await authFetch(`/api/claims/${rowId}`, {
        method: 'DELETE'
      });

      const payload = await response.json().catch(() => ({}));
      if (!response.ok) {
        throw new Error(payload.error || 'Failed to delete claim');
      }

      setClaims((previous) => previous.filter((claim) => claim._rowid_ !== rowId));
      if (editingClaim?._rowid_ === rowId) {
        closeEditModal();
      }
    } catch (err) {
      setError(err.message);
    } finally {
      setDeletingRowId(null);
    }
  }

  async function saveEdit() {
    if (!editingClaim?._rowid_) {
      return;
    }

    setIsSaving(true);
    setError('');

    try {
      const response = await authFetch(`/api/claims/${editingClaim._rowid_}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(editDraft)
      });

      const payload = await response.json().catch(() => ({}));
      if (!response.ok) {
        throw new Error(payload.error || 'Failed to save row');
      }

      setClaims((previous) => previous.map((claim) => (claim._rowid_ === payload._rowid_ ? payload : claim)));
      closeEditModal();
    } catch (err) {
      setError(err.message);
      setIsSaving(false);
    }
  }

  if (!token) {
    return (
      <main className="min-h-screen bg-slate-100 p-6 text-slate-800">
        <div className="mx-auto mt-16 w-full max-w-md rounded-xl bg-white p-6 shadow-lg">
          <h1 className="text-2xl font-bold">Logowanie</h1>
          <p className="mt-1 text-sm text-slate-500">Zaloguj się, aby zobaczyć reklamacje.</p>
          {error ? <p className="mt-3 text-sm font-medium text-red-600">{error}</p> : null}
          <form className="mt-5 space-y-4" onSubmit={login}>
            <div>
              <label className="mb-1 block text-sm font-medium">Login</label>
              <input
                value={loginForm.username}
                onChange={(event) => setLoginForm((prev) => ({ ...prev, username: event.target.value }))}
                className="w-full rounded border border-slate-300 px-3 py-2"
                placeholder="np. TODO"
              />
            </div>
            <div>
              <label className="mb-1 block text-sm font-medium">Hasło</label>
              <input
                type="password"
                value={loginForm.password}
                onChange={(event) => setLoginForm((prev) => ({ ...prev, password: event.target.value }))}
                className="w-full rounded border border-slate-300 px-3 py-2"
                placeholder="********"
              />
            </div>
            <button
              type="submit"
              disabled={authLoading}
              className="w-full rounded bg-blue-600 px-4 py-2 text-white hover:bg-blue-700 disabled:bg-blue-300"
            >
              {authLoading ? 'Logowanie...' : 'Zaloguj'}
            </button>
          </form>
        </div>
      </main>
    );
  }

  return (
    <main className="min-h-screen bg-slate-100 p-6 text-slate-800">
      <div className="mx-auto max-w-7xl rounded-xl bg-white p-6 shadow-lg">
        <header className="mb-6 flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">Reported Claims</h1>
            <p className="mt-1 text-sm text-slate-500">Użytkownik: {user?.fullName || user?.username} ({user?.role}) • DZIAŁ: {user?.dept || "-"}</p>
          </div>

          <div className="flex w-full flex-col gap-2 md:w-auto md:items-end">
            <div className="w-full md:w-80">
              <label htmlFor="filter" className="mb-1 block text-sm font-medium text-slate-700">
                Search all fields
              </label>
              <input
                id="filter"
                value={query}
                onChange={(event) => setQuery(event.target.value)}
                placeholder="Type to filter rows..."
                className="w-full rounded-md border border-slate-300 px-3 py-2 text-sm shadow-sm focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>
            <button onClick={logout} className="rounded border border-slate-300 px-3 py-2 text-sm hover:bg-slate-100">
              Wyloguj
            </button>
          </div>
        </header>

        <div className="mb-4 flex items-center justify-between gap-2">
          {!loading && !error && (
            <p className="text-sm text-slate-500">
              Showing <span className="font-semibold text-slate-700">{filteredClaims.length}</span> of{' '}
              <span className="font-semibold text-slate-700">{claims.length}</span> rows
            </p>
          )}

          <button
            onClick={openAddModal}
            disabled={loading}
            className="rounded bg-emerald-600 px-4 py-2 text-sm font-medium text-white hover:bg-emerald-700 disabled:cursor-not-allowed disabled:bg-emerald-300"
          >
            Dodaj niezgodność
          </button>
        </div>

        {loading ? <p className="text-slate-500">Loading claims...</p> : null}
        {error ? <p className="mb-3 font-medium text-red-600">{error}</p> : null}

        {!loading && (
          <div className="overflow-x-auto rounded-lg border border-slate-200">
            <table className="min-w-full divide-y divide-slate-200 text-sm">
              <thead className="bg-slate-50">
                <tr>
                  {displayColumns.map((column) => {
                    const isKkw = column.label === 'KKW';
                    const isTytul = column.label === 'TYTUL';

                    return (
                      <th
                        key={column.key}
                        className={`px-4 py-3 text-left font-semibold uppercase tracking-wide text-slate-600 ${
                          isKkw ? 'whitespace-nowrap w-44' : ''
                        } ${isTytul ? 'min-w-[26rem]' : ''}`}
                      >
                        {column.label === 'DZIAL' ? 'DZIAŁ' : column.label}
                      </th>
                    );
                  })}
                  <th className="px-4 py-3 text-left font-semibold uppercase tracking-wide text-slate-600">actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 bg-white">
                {filteredClaims.map((claim, index) => {
                  const rowId = claim._rowid_ ?? index;

                  return (
                    <tr key={rowId} className="hover:bg-slate-50">
                      {displayColumns.map((column) => {
                        const isKkw = column.label === 'KKW';
                        const isTytul = column.label === 'TYTUL';

                        return (
                          <td
                            key={`${rowId}-${column.key}`}
                            className={`px-4 py-3 align-top text-slate-700 ${
                              isKkw ? 'whitespace-nowrap w-44' : ''
                            } ${isTytul ? 'min-w-[26rem]' : ''}`}
                          >
                            {String(
                              column.lowerSource === '__dept__'
                                ? user?.dept || ''
                                : claim[column.source] ?? ''
                            )}
                          </td>
                        );
                      })}
                      <td className="px-4 py-3 whitespace-nowrap">
                        <div className="flex gap-2">
                          <button
                            onClick={() => openEditModal(claim)}
                            className="rounded border border-blue-300 px-3 py-1.5 text-blue-700 hover:bg-blue-50"
                          >
                            Edit
                          </button>
                          <button
                            onClick={() => deleteClaim(rowId)}
                            disabled={deletingRowId === rowId}
                            className="rounded border border-red-300 px-3 py-1.5 text-red-700 hover:bg-red-50 disabled:cursor-not-allowed disabled:opacity-50"
                          >
                            {deletingRowId === rowId ? 'Deleting...' : 'Delete'}
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })}
                {!filteredClaims.length && (
                  <tr>
                    <td className="px-4 py-8 text-center text-slate-500" colSpan={Math.max(displayColumns.length + 1, 1)}>
                      No rows match your search.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {isAddModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4">
          <div className="max-h-[90vh] w-full max-w-3xl overflow-hidden rounded-xl bg-white shadow-2xl">
            <div className="flex items-center justify-between border-b border-slate-200 px-6 py-4">
              <div>
                <h2 className="text-xl font-semibold text-slate-800">Dodaj niezgodność</h2>
                <p className="text-sm text-slate-500">Pole ZGLASZAJACY zostanie ustawione na aktualnie zalogowanego użytkownika.</p>
              </div>
              <button
                onClick={closeAddModal}
                disabled={isCreating}
                className="rounded border border-slate-300 px-3 py-1.5 text-slate-600 hover:bg-slate-100 disabled:opacity-50"
              >
                Close
              </button>
            </div>

            <div className="space-y-4 overflow-y-auto px-6 py-5">
              {showAutoFieldsSection && (
                <div className="rounded-md border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-900">
                  <p className="font-medium">Pola automatyczne:</p>
                  <ul className="list-disc pl-5">
                    <li>ID: autoincrement z bazy danych</li>
                    <li>data_zgloszenia: dzisiejsza data</li>
                    <li>status: Nowe</li>
                    <li>utworzono: aktualna data i czas</li>
                    <li>claim_number: format NZG-YYYY-001</li>
                    <li>zglaszajacy: {user?.fullName || user?.username}</li>
                    <li>dział: {user?.dept || '-'}</li>
                  </ul>
                </div>
              )}

              <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                {addFormColumns.map((column) => (
                  <div key={column} className="flex flex-col gap-1">
                    <label className="text-sm font-medium text-slate-700">{column}</label>
                    <input
                      value={newClaimDraft[column] ?? ''}
                      onChange={(event) =>
                        setNewClaimDraft((draft) => ({
                          ...draft,
                          [column]: event.target.value
                        }))
                      }
                      className="w-full rounded border border-slate-300 px-3 py-2 text-sm focus:border-emerald-500 focus:outline-none focus:ring-1 focus:ring-emerald-500"
                    />
                  </div>
                ))}
              </div>
            </div>

            <div className="flex justify-end gap-3 border-t border-slate-200 px-6 py-4">
              <button
                onClick={closeAddModal}
                disabled={isCreating}
                className="rounded border border-slate-300 px-4 py-2 text-slate-700 hover:bg-slate-100 disabled:cursor-not-allowed disabled:opacity-50"
              >
                Cancel
              </button>
              <button
                onClick={createClaim}
                disabled={isCreating}
                className="rounded bg-emerald-600 px-4 py-2 text-white hover:bg-emerald-700 disabled:cursor-not-allowed disabled:bg-emerald-300"
              >
                {isCreating ? 'Creating...' : 'Utwórz'}
              </button>
            </div>
          </div>
        </div>
      )}

      {editingClaim && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4">
          <div className="max-h-[90vh] w-full max-w-3xl overflow-hidden rounded-xl bg-white shadow-2xl">
            <div className="flex items-center justify-between border-b border-slate-200 px-6 py-4">
              <div>
                <h2 className="text-xl font-semibold text-slate-800">Edit claim</h2>
                <p className="text-sm text-slate-500">Row ID: {editingClaim._rowid_}</p>
              </div>
              <button
                onClick={closeEditModal}
                disabled={isSaving}
                className="rounded border border-slate-300 px-3 py-1.5 text-slate-600 hover:bg-slate-100 disabled:opacity-50"
              >
                Close
              </button>
            </div>

            <div className="max-h-[60vh] overflow-y-auto px-6 py-5">
              <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                {editableColumns.map((column) => (
                  <div key={column} className="flex flex-col gap-1">
                    <label className="text-sm font-medium text-slate-700">{column}</label>
                    <input
                      value={editDraft[column] ?? ''}
                      onChange={(event) =>
                        setEditDraft((draft) => ({
                          ...draft,
                          [column]: event.target.value
                        }))
                      }
                      className="w-full rounded border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
                    />
                  </div>
                ))}
              </div>
            </div>

            <div className="flex justify-end gap-3 border-t border-slate-200 px-6 py-4">
              <button
                onClick={closeEditModal}
                disabled={isSaving}
                className="rounded border border-slate-300 px-4 py-2 text-slate-700 hover:bg-slate-100 disabled:cursor-not-allowed disabled:opacity-50"
              >
                Cancel
              </button>
              <button
                onClick={saveEdit}
                disabled={isSaving}
                className="rounded bg-blue-600 px-4 py-2 text-white hover:bg-blue-700 disabled:cursor-not-allowed disabled:bg-blue-300"
              >
                {isSaving ? 'Saving...' : 'Save changes'}
              </button>
            </div>
          </div>
        </div>
      )}
    </main>
  );
}

export default App;
