import { useEffect, useMemo, useState } from 'react';

const autoGeneratedFields = new Set(['id', '_rowid_', 'claim_number', 'data_zgloszenia', 'status', 'utworzono']);

const mainListOrder = [
  'claim_number',
  'kkw',
  'kod_wyrobu',
  'nazwa_wyrobu',
  'tytul',
  'ilosc',
  'status',
  'zglaszajacy',
  'utworzono'
];

const hiddenMainListColumns = new Set(['_rowid_', 'id', 'opis', 'data_zgloszenia']);

function App() {
  const [claims, setClaims] = useState([]);
  const [schema, setSchema] = useState([]);
  const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [editingClaim, setEditingClaim] = useState(null);
  const [editDraft, setEditDraft] = useState({});
  const [isSaving, setIsSaving] = useState(false);
  const [isAddModalOpen, setIsAddModalOpen] = useState(false);
  const [newClaimDraft, setNewClaimDraft] = useState({});
  const [isCreating, setIsCreating] = useState(false);

  useEffect(() => {
    async function loadInitialData() {
      try {
        const [claimsResponse, schemaResponse] = await Promise.all([
          fetch('/api/claims'),
          fetch('/api/claims/schema')
        ]);

        if (!claimsResponse.ok) {
          throw new Error('Could not load claims');
        }
        if (!schemaResponse.ok) {
          throw new Error('Could not load schema');
        }

        const claimsData = await claimsResponse.json();
        const schemaData = await schemaResponse.json();

        setClaims(claimsData);
        setSchema(Array.isArray(schemaData) ? schemaData : []);
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    }

    loadInitialData();
  }, []);

  const columns = useMemo(() => {
    if (claims[0]) {
      return Object.keys(claims[0]);
    }

    if (!schema.length) {
      return [];
    }

    return ['_rowid_', ...schema.map((column) => column.name)];
  }, [claims, schema]);

  const editableColumns = useMemo(() => columns.filter((column) => column !== '_rowid_'), [columns]);

  const displayColumns = useMemo(() => {
    const lowerToActual = new Map();
    columns.forEach((column) => {
      const lower = column.toLowerCase();
      if (!lowerToActual.has(lower)) {
        lowerToActual.set(lower, column);
      }
    });

    const ordered = mainListOrder
      .filter((column) => lowerToActual.has(column))
      .map((column) => lowerToActual.get(column));

    const extras = columns.filter((column) => {
      const lower = column.toLowerCase();
      return !hiddenMainListColumns.has(lower) && !mainListOrder.includes(lower);
    });

    return [...ordered, ...extras];
  }, [columns]);

  const addFormColumns = useMemo(() => {
    if (schema.length) {
      return schema
        .map((column) => column.name)
        .filter((column) => !autoGeneratedFields.has(column));
    }

    return editableColumns.filter((column) => !autoGeneratedFields.has(column));
  }, [editableColumns, schema]);

  const filteredClaims = useMemo(() => {
    if (!query.trim()) {
      return claims;
    }

    const needle = query.toLowerCase();
    return claims.filter((claim) =>
      Object.values(claim).some((value) => String(value ?? '').toLowerCase().includes(needle))
    );
  }, [claims, query]);

  function openEditModal(claim) {
    setEditingClaim(claim);
    const draft = {};
    editableColumns.forEach((column) => {
      draft[column] = String(claim[column] ?? '');
    });
    setEditDraft(draft);
    setError('');
  }

  function closeEditModal() {
    setEditingClaim(null);
    setEditDraft({});
    setIsSaving(false);
  }

  function openAddModal() {
    const draft = {};
    addFormColumns.forEach((column) => {
      draft[column] = '';
    });
    setNewClaimDraft(draft);
    setIsAddModalOpen(true);
    setError('');
  }

  function closeAddModal() {
    setIsAddModalOpen(false);
    setNewClaimDraft({});
    setIsCreating(false);
  }

  async function createClaim() {
    setIsCreating(true);
    setError('');

    try {
      const response = await fetch('/api/claims', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(newClaimDraft)
      });

      if (!response.ok) {
        const payload = await response.json().catch(() => ({}));
        throw new Error(payload.error || 'Failed to create claim');
      }

      const createdRow = await response.json();
      setClaims((previous) => [createdRow, ...previous]);
      closeAddModal();
    } catch (err) {
      setError(err.message);
      setIsCreating(false);
    }
  }

  async function saveEdit() {
    if (!editingClaim?._rowid_) {
      return;
    }

    setIsSaving(true);
    setError('');

    try {
      const response = await fetch(`/api/claims/${editingClaim._rowid_}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(editDraft)
      });

      if (!response.ok) {
        const payload = await response.json().catch(() => ({}));
        throw new Error(payload.error || 'Failed to save row');
      }

      const updatedRow = await response.json();
      setClaims((previous) =>
        previous.map((claim) => (claim._rowid_ === updatedRow._rowid_ ? updatedRow : claim))
      );
      closeEditModal();
    } catch (err) {
      setError(err.message);
      setIsSaving(false);
    }
  }

  return (
    <main className="min-h-screen bg-slate-100 p-6 text-slate-800">
      <div className="mx-auto max-w-7xl rounded-xl bg-white p-6 shadow-lg">
        <header className="mb-6 flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">Reported Claims</h1>
            <p className="mt-1 text-sm text-slate-500">Table: reklamacje</p>
          </div>

          <div className="w-full md:max-w-sm">
            <label htmlFor="filter" className="mb-1 block text-sm font-medium text-slate-700">
              Search all fields
            </label>
            <input
              id="filter"
              value={query}
              onChange={(event) => setQuery(event.target.value)}
              placeholder="Type to filter rows..."
              className="w-full rounded-md border border-slate-300 px-3 py-2 text-sm shadow-sm focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>
        </header>

        <div className="mb-4 flex items-center justify-between gap-2">
          {!loading && !error && (
            <p className="text-sm text-slate-500">
              Showing <span className="font-semibold text-slate-700">{filteredClaims.length}</span> of{' '}
              <span className="font-semibold text-slate-700">{claims.length}</span> rows
            </p>
          )}

          <button
            onClick={openAddModal}
            disabled={loading}
            className="rounded bg-emerald-600 px-4 py-2 text-sm font-medium text-white hover:bg-emerald-700 disabled:cursor-not-allowed disabled:bg-emerald-300"
          >
            Dodaj niezgodność
          </button>
        </div>

        {loading ? <p className="text-slate-500">Loading claims...</p> : null}
        {error ? <p className="mb-3 font-medium text-red-600">{error}</p> : null}

        {!loading && (
          <div className="overflow-x-auto rounded-lg border border-slate-200">
            <table className="min-w-full divide-y divide-slate-200 text-sm">
              <thead className="bg-slate-50">
                <tr>
                  {displayColumns.map((column) => (
                    <th key={column} className="px-4 py-3 text-left font-semibold uppercase tracking-wide text-slate-600">
                      {column}
                    </th>
                  ))}
                  <th className="px-4 py-3 text-left font-semibold uppercase tracking-wide text-slate-600">actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 bg-white">
                {filteredClaims.map((claim, index) => {
                  const rowId = claim._rowid_ ?? index;

                  return (
                    <tr key={rowId} className="hover:bg-slate-50">
                      {displayColumns.map((column) => (
                        <td key={`${rowId}-${column}`} className="px-4 py-3 align-top text-slate-700">
                          {String(claim[column] ?? '')}
                        </td>
                      ))}
                      <td className="px-4 py-3 whitespace-nowrap">
                        <button
                          onClick={() => openEditModal(claim)}
                          className="rounded border border-blue-300 px-3 py-1.5 text-blue-700 hover:bg-blue-50"
                        >
                          Edit
                        </button>
                      </td>
                    </tr>
                  );
                })}
                {!filteredClaims.length && (
                  <tr>
                    <td className="px-4 py-8 text-center text-slate-500" colSpan={Math.max(displayColumns.length + 1, 1)}>
                      No rows match your search.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {isAddModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4">
          <div className="max-h-[90vh] w-full max-w-3xl overflow-hidden rounded-xl bg-white shadow-2xl">
            <div className="flex items-center justify-between border-b border-slate-200 px-6 py-4">
              <div>
                <h2 className="text-xl font-semibold text-slate-800">Dodaj niezgodność</h2>
                <p className="text-sm text-slate-500">Wypełnij formularz. Część pól zostanie ustawiona automatycznie.</p>
              </div>
              <button
                onClick={closeAddModal}
                disabled={isCreating}
                className="rounded border border-slate-300 px-3 py-1.5 text-slate-600 hover:bg-slate-100 disabled:opacity-50"
              >
                Close
              </button>
            </div>

            <div className="space-y-4 overflow-y-auto px-6 py-5">
              <div className="rounded-md border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-900">
                <p className="font-medium">Pola automatyczne:</p>
                <ul className="list-disc pl-5">
                  <li>ID: autoincrement z bazy danych</li>
                  <li>data_zgloszenia: dzisiejsza data</li>
                  <li>status: Nowe</li>
                  <li>utworzono: aktualna data i czas</li>
                  <li>claim_number: format NZG-YYYY-001</li>
                </ul>
              </div>

              <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                {addFormColumns.map((column) => (
                  <div key={column} className="flex flex-col gap-1">
                    <label className="text-sm font-medium text-slate-700">{column}</label>
                    <input
                      value={newClaimDraft[column] ?? ''}
                      onChange={(event) =>
                        setNewClaimDraft((draft) => ({
                          ...draft,
                          [column]: event.target.value
                        }))
                      }
                      className="w-full rounded border border-slate-300 px-3 py-2 text-sm focus:border-emerald-500 focus:outline-none focus:ring-1 focus:ring-emerald-500"
                    />
                  </div>
                ))}
              </div>
            </div>

            <div className="flex justify-end gap-3 border-t border-slate-200 px-6 py-4">
              <button
                onClick={closeAddModal}
                disabled={isCreating}
                className="rounded border border-slate-300 px-4 py-2 text-slate-700 hover:bg-slate-100 disabled:cursor-not-allowed disabled:opacity-50"
              >
                Cancel
              </button>
              <button
                onClick={createClaim}
                disabled={isCreating}
                className="rounded bg-emerald-600 px-4 py-2 text-white hover:bg-emerald-700 disabled:cursor-not-allowed disabled:bg-emerald-300"
              >
                {isCreating ? 'Creating...' : 'Utwórz'}
              </button>
            </div>
          </div>
        </div>
      )}

      {editingClaim && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4">
          <div className="max-h-[90vh] w-full max-w-3xl overflow-hidden rounded-xl bg-white shadow-2xl">
            <div className="flex items-center justify-between border-b border-slate-200 px-6 py-4">
              <div>
                <h2 className="text-xl font-semibold text-slate-800">Edit claim</h2>
                <p className="text-sm text-slate-500">Row ID: {editingClaim._rowid_}</p>
              </div>
              <button
                onClick={closeEditModal}
                disabled={isSaving}
                className="rounded border border-slate-300 px-3 py-1.5 text-slate-600 hover:bg-slate-100 disabled:opacity-50"
              >
                Close
              </button>
            </div>

            <div className="max-h-[60vh] overflow-y-auto px-6 py-5">
              <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                {editableColumns.map((column) => (
                  <div key={column} className="flex flex-col gap-1">
                    <label className="text-sm font-medium text-slate-700">{column}</label>
                    <input
                      value={editDraft[column] ?? ''}
                      onChange={(event) =>
                        setEditDraft((draft) => ({
                          ...draft,
                          [column]: event.target.value
                        }))
                      }
                      className="w-full rounded border border-slate-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
                    />
                  </div>
                ))}
              </div>
            </div>

            <div className="flex justify-end gap-3 border-t border-slate-200 px-6 py-4">
              <button
                onClick={closeEditModal}
                disabled={isSaving}
                className="rounded border border-slate-300 px-4 py-2 text-slate-700 hover:bg-slate-100 disabled:cursor-not-allowed disabled:opacity-50"
              >
                Cancel
              </button>
              <button
                onClick={saveEdit}
                disabled={isSaving}
                className="rounded bg-blue-600 px-4 py-2 text-white hover:bg-blue-700 disabled:cursor-not-allowed disabled:bg-blue-300"
              >
                {isSaving ? 'Saving...' : 'Save changes'}
              </button>
            </div>
          </div>
        </div>
      )}
    </main>
  );
}

export default App;
